env:
  AWS_DEFAULT_REGION: "ap-southeast-2"

steps:
  - name: ':packer: pack'
    command: 'make pack'
    artifact_paths: 'packer/TestResults.xml,packer/manifest.json'

  - wait

  - name: ':hammer: test'
    command: 'make test'
